apiVersion: apps/v1
kind: Deployment
metadata:
  name: cantcost
  namespace: catalyst-canton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cantcost
  template:
    metadata:
      labels:
        app: cantcost
    spec:
      serviceAccountName: cantcost-sa
      containers:
        - name: cantcost
          image: {image}
          imagePullPolicy: IfNotPresent
          env:
            # Deployment whose pods' logs you want to read
            - name: TARGET_DEPLOYMENT
              value: "deployment-1"
            # Used by the app to default to its own namespace
            - name: TARGET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: EXPORTER_TYPE
              value: "http"
            - name: HTTP_EXPORTER_URL
              value: "https://targetdomain/anything"
            - name: HTTP_EXPORTER_AUTH_HEADER
              value: "{secret}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cantcost-sa
  namespace: catalyst-canton
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cantcost-role
  namespace: catalyst-canton
rules:
  # For pods & logs
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  # For deployments
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cantcost-rb
  namespace: catalyst-canton
subjects:
  - kind: ServiceAccount
    name: cantcost-sa
    namespace: catalyst-canton
roleRef:
  kind: Role
  name: cantcost-role
  apiGroup: rbac.authorization.k8s.io
